spring.datasource.url=jdbc:postgresql://localhost:5432/orcamentos_grafica
spring.datasource.username=postgres
spring.datasource.password=1001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

google.drive.folder-id=1tWT0FXT7ZvHqkBY-8LFtIdNQzJXPyXdF
google.oauth.credentials-path=${GOOGLE_OAUTH_CREDENTIALS_PATH}
google.oauth.tokens-path=${GOOGLE_OAUTH_TOKENS_PATH}

#spring.sql.init.mode=always